// Auto-generated by s4extract. Safe to delete after materials are fixed.
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class S4ExtractMaterialFixer_bd3cc5b3a3
{
    struct Entry
    {
        public string materialName;
        public string albedoName;
        public string normalName;
        public string maskName;
        public Entry(string m, string a, string n, string mask) { materialName = m; albedoName = a; normalName = n; maskName = mask; }
    }

    struct MeshMaterial
    {
        public string meshName;
        public string materialName;
        public MeshMaterial(string mesh, string mat) { meshName = mesh; materialName = mat; }
    }

    struct PartAsset
    {
        public string assetName;
        public string materialName;
        public PartAsset(string asset, string mat) { assetName = asset; materialName = mat; }
    }

    struct BreakSpec
    {
        public string intactAssetName;
        public string materialName;
        public string[] brokenAssetNames;
        public BreakSpec(string intactAsset, string mat, string[] brokenAssets) { intactAssetName = intactAsset; materialName = mat; brokenAssetNames = brokenAssets; }
    }

    static readonly Entry[] Entries = new Entry[]
    {
        new Entry("1_mlod00_g01_swatch00_material", "1_tex00", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch01_material", "1_tex03", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch02_material", "1_tex04", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch03_material", "1_tex05", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch04_material", "1_tex06", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch05_material", "1_tex07", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch06_material", "1_tex08", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch07_material", "1_tex09", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch08_material", "1_tex10", "1_tex01", ""),
        new Entry("1_mlod00_g01_swatch09_material", "1_tex11", "1_tex01", ""),
        new Entry("1_mlod00_g02_swatch00_material", "1_tex12", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch01_material", "1_tex15", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch02_material", "1_tex12", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch03_material", "1_tex12", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch04_material", "1_tex12", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch05_material", "1_tex15", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch06_material", "1_tex15", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch07_material", "1_tex15", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch08_material", "1_tex12", "1_tex13", ""),
        new Entry("1_mlod00_g02_swatch09_material", "1_tex12", "1_tex13", ""),
    };

    static readonly string[] MeshNames = new string[]
    {
        "1_mlod00_g01",
        "1_mlod00_g02",
    };

    static readonly MeshMaterial[] MeshMaterials = new MeshMaterial[]
    {
        new MeshMaterial("1_mlod00_g01", "1_mlod00_g01_swatch00_material"),
        new MeshMaterial("1_mlod00_g02", "1_mlod00_g02_swatch00_material"),
    };

    static readonly PartAsset[] PartAssets = new PartAsset[]
    {
        new PartAsset("1_mlod00_g01", "1_mlod00_g01_swatch00_material"),
        new PartAsset("1_mlod00_g02", "1_mlod00_g02_swatch00_material"),
    };

    static readonly BreakSpec[] BreakSpecs = new BreakSpec[]
    {

    };

    static S4ExtractMaterialFixer_bd3cc5b3a3()
    {
        EditorApplication.delayCall += FixAll;
    }

    [MenuItem("Tools/s4extract/Fix Sims 4 Materials")]
    public static void FixAll()
    {
        Shader shader = FindBestShader();
        if (shader == null)
        {
            Debug.LogWarning("s4extract: could not find HDRP/Lit, URP/Lit or Standard shader in this project.");
            return;
        }

        int changed = 0;
        foreach (Entry e in Entries)
        {
            Material mat = FindMaterial(e.materialName);
            Texture albedo = FindTexture(e.albedoName);
            Texture normal = FindTexture(e.normalName);
            Texture mask = FindTexture(e.maskName);
            if (mat == null) continue;

            mat.shader = shader;
            if (albedo != null)
            {
                SetTex(mat, "_BaseColorMap", albedo); // HDRP
                SetTex(mat, "_BaseMap", albedo);      // URP
                SetTex(mat, "_MainTex", albedo);      // Built-in fallback
            }
            if (normal != null)
            {
                MakeNormalMap(normal);
                SetTex(mat, "_NormalMap", normal); // HDRP
                SetTex(mat, "_BumpMap", normal);   // URP/Built-in
                mat.EnableKeyword("_NORMALMAP");
                mat.EnableKeyword("_NORMALMAP_TANGENT_SPACE");
            }
            if (mask != null)
            {
                SetTex(mat, "_MaskMap", mask);             // HDRP mask map
                SetTex(mat, "_MetallicGlossMap", mask);    // URP/Built-in-ish fallback
            }
            SetColor(mat, "_BaseColor", Color.white);
            SetColor(mat, "_Color", Color.white);
            SetFloat(mat, "_Metallic", 0f);
            SetFloat(mat, "_Smoothness", 0.5f);
            SetFloat(mat, "_NormalScale", 1f);
            SetFloat(mat, "_BumpScale", 1f);
            SetFloat(mat, "_SurfaceType", 0f); // HDRP opaque
            SetFloat(mat, "_Surface", 0f);     // URP opaque
            mat.renderQueue = -1;
            EditorUtility.SetDirty(mat);
            changed++;
        }

        int assigned = AssignMappedMaterialsToSceneMeshes();
        string partsPrefab = CreatePartsPrefab();

        if (changed > 0 || assigned > 0 || !string.IsNullOrEmpty(partsPrefab))
        {
            AssetDatabase.SaveAssets();
            Debug.Log("s4extract: fixed " + changed + " material(s), assigned mapped materials to " + assigned + " renderer(s), parts prefab: " + partsPrefab + ", shader: " + shader.name);
        }
    }

    static string CreateReadyPrefab()
    {
        if (Entries.Length == 0 || MeshNames.Length == 0) return "";
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return "";

        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/1_READY.prefab";

        GameObject root = new GameObject("1_READY");
        int added = 0;
        foreach (string mn in MeshNames)
        {
            GameObject model = FindModelAsset(mn);
            if (model == null) continue;
            Material target = FindPreferredMaterialForMesh(mn) ?? first;
            GameObject child = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (child == null) child = Object.Instantiate(model);
            child.name = mn;
            child.transform.SetParent(root.transform, false);
            foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
            {
                Material[] mats = r.sharedMaterials;
                if (mats == null || mats.Length == 0) mats = new Material[] { target };
                for (int i = 0; i < mats.Length; i++) mats[i] = target;
                r.sharedMaterials = mats;
            }
            added++;
        }

        if (added == 0)
        {
            Object.DestroyImmediate(root);
            return "";
        }

        PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);
        return prefabPath;
    }

    static string CreatePartsPrefab()
    {
        if (Entries.Length == 0 || PartAssets.Length == 0) return "";
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return "";

        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/1_PARTS.prefab";

        GameObject root = new GameObject("1_PARTS");
        int added = 0;
        foreach (PartAsset pa in PartAssets)
        {
            GameObject model = FindModelAsset(pa.assetName);
            if (model == null) continue;
            Material target = FindMaterial(pa.materialName) ?? first;

            GameObject pieceRoot = new GameObject(pa.assetName);
            pieceRoot.transform.SetParent(root.transform, false);
            var breakable = pieceRoot.AddComponent<S4BreakablePart>();
            breakable.breakOnCollision = false;
            breakable.breakImpulseThreshold = 8f;

            GameObject intact = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (intact == null) intact = Object.Instantiate(model);
            intact.name = "Intact";
            intact.transform.SetParent(pieceRoot.transform, false);
            ApplyMaterialAndPhysics(intact, target, 2f);
            breakable.intactRoot = intact;

            BreakSpec spec;
            var brokenRoots = new System.Collections.Generic.List<GameObject>();
            if (TryGetBreakSpec(pa.assetName, out spec) && spec.brokenAssetNames != null)
            {
                for (int i = 0; i < spec.brokenAssetNames.Length; i++)
                {
                    string brokenAssetName = spec.brokenAssetNames[i];
                    GameObject brokenModel = FindModelAsset(brokenAssetName);
                    if (brokenModel == null) continue;
                    GameObject broken = (GameObject)PrefabUtility.InstantiatePrefab(brokenModel);
                    if (broken == null) broken = Object.Instantiate(brokenModel);
                    broken.name = "Broken_" + i;
                    broken.transform.SetParent(pieceRoot.transform, false);
                    ApplyMaterialAndPhysics(broken, target, 1f);
                    broken.SetActive(false);
                    brokenRoots.Add(broken);
                }
            }
            breakable.brokenRoots = brokenRoots.ToArray();
            added++;
        }

        if (added == 0)
        {
            Object.DestroyImmediate(root);
            return "";
        }

        PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);
        return prefabPath;
    }

    static bool TryGetBreakSpec(string intactAssetName, out BreakSpec spec)
    {
        foreach (BreakSpec bs in BreakSpecs)
        {
            if (bs.intactAssetName == intactAssetName)
            {
                spec = bs;
                return true;
            }
        }
        spec = default;
        return false;
    }

    static void ApplyMaterialAndPhysics(GameObject root, Material target, float mass)
    {
        foreach (Renderer r in root.GetComponentsInChildren<Renderer>(true))
        {
            Material[] mats = r.sharedMaterials;
            if (mats == null || mats.Length == 0) mats = new Material[] { target };
            for (int i = 0; i < mats.Length; i++) mats[i] = target;
            r.sharedMaterials = mats;
        }

        Rigidbody rb = root.GetComponent<Rigidbody>();
        if (rb == null) rb = root.AddComponent<Rigidbody>();
        rb.mass = mass;
        rb.linearDamping = 0.05f;
        rb.angularDamping = 0.05f;
        rb.useGravity = true;
        rb.isKinematic = false;
        rb.interpolation = RigidbodyInterpolation.Interpolate;
        rb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;

        foreach (MeshFilter mf in root.GetComponentsInChildren<MeshFilter>(true))
        {
            if (mf.sharedMesh == null) continue;
            MeshCollider mc = mf.GetComponent<MeshCollider>();
            if (mc == null) mc = mf.gameObject.AddComponent<MeshCollider>();
            mc.sharedMesh = mf.sharedMesh;
            mc.convex = true;
        }
    }

    static string CreateBreakablePrefab()
    {
        if (Entries.Length == 0 || BreakSpecs.Length == 0) return "";
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return "";

        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/1_BREAKABLE.prefab";

        GameObject root = new GameObject("1_BREAKABLE");
        int added = 0;
        foreach (BreakSpec bs in BreakSpecs)
        {
            GameObject intactModel = FindModelAsset(bs.intactAssetName);
            if (intactModel == null || bs.brokenAssetNames == null || bs.brokenAssetNames.Length == 0) continue;
            Material target = FindMaterial(bs.materialName) ?? first;

            GameObject pieceRoot = new GameObject(bs.intactAssetName);
            pieceRoot.transform.SetParent(root.transform, false);
            var breakable = pieceRoot.AddComponent<S4BreakablePart>();
            breakable.breakOnCollision = false;
            breakable.breakImpulseThreshold = 8f;

            GameObject intact = (GameObject)PrefabUtility.InstantiatePrefab(intactModel);
            if (intact == null) intact = Object.Instantiate(intactModel);
            intact.name = "Intact";
            intact.transform.SetParent(pieceRoot.transform, false);
            foreach (Renderer r in intact.GetComponentsInChildren<Renderer>(true))
            {
                Material[] mats = r.sharedMaterials;
                if (mats == null || mats.Length == 0) mats = new Material[] { target };
                for (int i = 0; i < mats.Length; i++) mats[i] = target;
                r.sharedMaterials = mats;
            }
            Rigidbody intactRb = intact.GetComponent<Rigidbody>();
            if (intactRb == null) intactRb = intact.AddComponent<Rigidbody>();
            intactRb.mass = 2f;
            intactRb.linearDamping = 0.05f;
            intactRb.angularDamping = 0.05f;
            intactRb.useGravity = true;
            intactRb.isKinematic = false;
            intactRb.interpolation = RigidbodyInterpolation.Interpolate;
            intactRb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;
            foreach (MeshFilter mf in intact.GetComponentsInChildren<MeshFilter>(true))
            {
                if (mf.sharedMesh == null) continue;
                MeshCollider mc = mf.GetComponent<MeshCollider>();
                if (mc == null) mc = mf.gameObject.AddComponent<MeshCollider>();
                mc.sharedMesh = mf.sharedMesh;
                mc.convex = true;
            }

            var brokenRoots = new System.Collections.Generic.List<GameObject>();
            foreach (string brokenName in bs.brokenAssetNames)
            {
                GameObject brokenModel = FindModelAsset(brokenName);
                if (brokenModel == null) continue;
                GameObject broken = (GameObject)PrefabUtility.InstantiatePrefab(brokenModel);
                if (broken == null) broken = Object.Instantiate(brokenModel);
                broken.name = brokenName;
                broken.transform.SetParent(pieceRoot.transform, false);
                foreach (Renderer r in broken.GetComponentsInChildren<Renderer>(true))
                {
                    Material[] mats = r.sharedMaterials;
                    if (mats == null || mats.Length == 0) mats = new Material[] { target };
                    for (int i = 0; i < mats.Length; i++) mats[i] = target;
                    r.sharedMaterials = mats;
                }
                Rigidbody rb = broken.GetComponent<Rigidbody>();
                if (rb == null) rb = broken.AddComponent<Rigidbody>();
                rb.mass = 1f;
                rb.linearDamping = 0.05f;
                rb.angularDamping = 0.05f;
                rb.useGravity = true;
                rb.isKinematic = false;
                rb.interpolation = RigidbodyInterpolation.Interpolate;
                rb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;
                foreach (MeshFilter mf in broken.GetComponentsInChildren<MeshFilter>(true))
                {
                    if (mf.sharedMesh == null) continue;
                    MeshCollider mc = mf.GetComponent<MeshCollider>();
                    if (mc == null) mc = mf.gameObject.AddComponent<MeshCollider>();
                    mc.sharedMesh = mf.sharedMesh;
                    mc.convex = true;
                }
                broken.SetActive(false);
                brokenRoots.Add(broken);
            }

            breakable.intactRoot = intact;
            breakable.brokenRoots = brokenRoots.ToArray();
            added++;
        }

        if (added == 0)
        {
            Object.DestroyImmediate(root);
            return "";
        }

        PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);
        return prefabPath;
    }

    static int AssignMappedMaterialsToSceneMeshes()
    {
        if (Entries.Length == 0 || MeshNames.Length == 0) return 0;
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return 0;
        int assigned = 0;
#if UNITY_2023_1_OR_NEWER
        Renderer[] renderers = Object.FindObjectsByType<Renderer>(FindObjectsInactive.Include, FindObjectsSortMode.None);
#else
        Renderer[] renderers = Object.FindObjectsOfType<Renderer>(true);
#endif
        foreach (Renderer r in renderers)
        {
            string goName = r.gameObject.name;
            Material target = FindPreferredMaterialForMesh(goName);
            if (target == null)
            {
                foreach (string mn in MeshNames)
                {
                    if (goName == mn || goName.StartsWith(mn))
                    {
                        target = FindPreferredMaterialForMesh(mn) ?? first;
                        break;
                    }
                }
            }
            if (target == null) continue;
            Material[] mats = r.sharedMaterials;
            if (mats == null || mats.Length == 0) mats = new Material[] { target };
            for (int i = 0; i < mats.Length; i++) mats[i] = target;
            r.sharedMaterials = mats;
            EditorUtility.SetDirty(r);
            assigned++;
        }
        if (assigned > 0) MarkOpenScenesDirty();
        return assigned;
    }

    static void MarkOpenScenesDirty()
    {
        for (int i = 0; i < SceneManager.sceneCount; i++)
        {
            var scene = SceneManager.GetSceneAt(i);
            if (scene.isLoaded) UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
        }
    }

    static Material FindPreferredMaterialForMesh(string meshOrGoName)
    {
        if (string.IsNullOrEmpty(meshOrGoName)) return null;
        foreach (MeshMaterial mm in MeshMaterials)
        {
            if (meshOrGoName == mm.meshName || meshOrGoName.StartsWith(mm.meshName))
            {
                Material m = FindMaterial(mm.materialName);
                if (m != null) return m;
            }
        }
        return null;
    }

    static Shader FindBestShader()
    {
        string preferred = "hdrp";
        if (preferred == "hdrp")
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (preferred == "urp")
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }
        if (preferred == "builtin")
        {
            Shader s = Shader.Find("Standard");
            if (s != null) return s;
        }

        RenderPipelineAsset rp = GraphicsSettings.currentRenderPipeline;
        string rpName = rp != null ? rp.GetType().Name.ToLowerInvariant() : "";
        if (rpName.Contains("hd"))
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (rpName.Contains("universal") || rpName.Contains("urp"))
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }

        string[] candidates = new string[] { "HDRP/Lit", "Universal Render Pipeline/Lit", "Standard" };
        foreach (string c in candidates)
        {
            Shader s = Shader.Find(c);
            if (s != null) return s;
        }
        return null;
    }

    static Material FindMaterial(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name + " t:Material");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Material m = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (m != null && m.name == name) return m;
        }
        return null;
    }

    static GameObject FindModelAsset(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name);

        // Prefer OBJ for the auto-created READY prefab: Unity imports OBJ at
        // 1:1 scale and its face UVs are simple/reliable. FBX is still exported
        // beside it for external tools, but Unity's FBX importer may apply a
        // 0.01 file scale depending on FBX unit metadata.
        foreach (string ext in new string[] { ".obj", ".fbx" })
        {
            foreach (string g in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                if (!path.ToLowerInvariant().EndsWith(ext)) continue;
                GameObject go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null && (go.name == name || Path.GetFileNameWithoutExtension(path) == name)) return go;
            }
        }
        return null;
    }

    static Texture FindTexture(string nameNoExt)
    {
        if (string.IsNullOrEmpty(nameNoExt)) return null;
        string[] guids = AssetDatabase.FindAssets(nameNoExt + " t:Texture2D");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Texture t = AssetDatabase.LoadAssetAtPath<Texture>(path);
            if (t != null && t.name == nameNoExt) return t;
        }
        return null;
    }

    static void MakeNormalMap(Texture tex)
    {
        string path = AssetDatabase.GetAssetPath(tex);
        TextureImporter ti = AssetImporter.GetAtPath(path) as TextureImporter;
        if (ti != null && ti.textureType != TextureImporterType.NormalMap)
        {
            ti.textureType = TextureImporterType.NormalMap;
            ti.SaveAndReimport();
        }
    }

    static void SetTex(Material m, string prop, Texture t)
    {
        if (m.HasProperty(prop)) m.SetTexture(prop, t);
    }

    static void SetColor(Material m, string prop, Color c)
    {
        if (m.HasProperty(prop)) m.SetColor(prop, c);
    }

    static void SetFloat(Material m, string prop, float v)
    {
        if (m.HasProperty(prop)) m.SetFloat(prop, v);
    }
}
#endif
